# Generated by Django 5.1.3 on 2024-11-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('domain', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('task_file', models.FileField(blank=True, null=True, upload_to='tasks/')),
                ('task_status', models.BooleanField(default=False)),
                ('certificate_issued', models.BooleanField(default=False)),
            ],
        ),
    ]
